package com.pasantia.entidades;
// Generated 14/08/2013 07:56:36 AM by Hibernate Tools 3.2.1.GA



/**
 * CargadosCsv generated by hbm2java
 */
public class CargadosCsv  implements java.io.Serializable {


     private Integer idnewTable;
     private Integer divipola;
     private Integer codDepto;
     private Integer codMpio;
     private String dpto;
     private String nomMpio;
     private String nomPoblad;

    public CargadosCsv() {
    }

    public CargadosCsv(Integer divipola, Integer codDepto, Integer codMpio, String dpto, String nomMpio, String nomPoblad) {
       this.divipola = divipola;
       this.codDepto = codDepto;
       this.codMpio = codMpio;
       this.dpto = dpto;
       this.nomMpio = nomMpio;
       this.nomPoblad = nomPoblad;
    }
   
    public Integer getIdnewTable() {
        return this.idnewTable;
    }
    
    public void setIdnewTable(Integer idnewTable) {
        this.idnewTable = idnewTable;
    }
    public Integer getDivipola() {
        return this.divipola;
    }
    
    public void setDivipola(Integer divipola) {
        this.divipola = divipola;
    }
    public Integer getCodDepto() {
        return this.codDepto;
    }
    
    public void setCodDepto(Integer codDepto) {
        this.codDepto = codDepto;
    }
    public Integer getCodMpio() {
        return this.codMpio;
    }
    
    public void setCodMpio(Integer codMpio) {
        this.codMpio = codMpio;
    }
    public String getDpto() {
        return this.dpto;
    }
    
    public void setDpto(String dpto) {
        this.dpto = dpto;
    }
    public String getNomMpio() {
        return this.nomMpio;
    }
    
    public void setNomMpio(String nomMpio) {
        this.nomMpio = nomMpio;
    }
    public String getNomPoblad() {
        return this.nomPoblad;
    }
    
    public void setNomPoblad(String nomPoblad) {
        this.nomPoblad = nomPoblad;
    }




}


