package com.pasantia.entidades;
// Generated 10/07/2013 10:05:50 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Casino generated by hbm2java
 */
public class Casino  implements java.io.Serializable {


     private Integer idCasino;
     private Persona persona;
     private Ciudad ciudad;
     private String nombre;
     private String direccion;
     private String nit;
     private Set productos = new HashSet(0);

    public Casino() {
    }

	
    public Casino(Persona persona, Ciudad ciudad, String nombre, String direccion, String nit) {
        this.persona = persona;
        this.ciudad = ciudad;
        this.nombre = nombre;
        this.direccion = direccion;
        this.nit = nit;
    }
    public Casino(Persona persona, Ciudad ciudad, String nombre, String direccion, String nit, Set productos) {
       this.persona = persona;
       this.ciudad = ciudad;
       this.nombre = nombre;
       this.direccion = direccion;
       this.nit = nit;
       this.productos = productos;
    }
   
    public Integer getIdCasino() {
        return this.idCasino;
    }
    
    public void setIdCasino(Integer idCasino) {
        this.idCasino = idCasino;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


