package com.pasantia.entidades;
// Generated 10/07/2013 05:30:45 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer idCiudad;
     private Departamento departamento;
     private String nombreCiudad;
     private Set personas = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(Departamento departamento, String nombreCiudad) {
        this.departamento = departamento;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(Departamento departamento, String nombreCiudad, Set personas) {
       this.departamento = departamento;
       this.nombreCiudad = nombreCiudad;
       this.personas = personas;
    }
   
    public Integer getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


