package com.pasantia.entidades;
// Generated 14/08/2013 07:56:36 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer idCiudad;
     private Departamento departamento;
     private String nombreCiudad;
     private Double latitud;
     private Double longitud;
     private Set personas = new HashSet(0);
     private Set batallons = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(Departamento departamento, String nombreCiudad) {
        this.departamento = departamento;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(Departamento departamento, String nombreCiudad, Double latitud, Double longitud, Set personas, Set batallons) {
       this.departamento = departamento;
       this.nombreCiudad = nombreCiudad;
       this.latitud = latitud;
       this.longitud = longitud;
       this.personas = personas;
       this.batallons = batallons;
    }
   
    public Integer getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }
    public Set getBatallons() {
        return this.batallons;
    }
    
    public void setBatallons(Set batallons) {
        this.batallons = batallons;
    }




}


