package com.pasantia.entidades;
// Generated 10/07/2013 05:30:45 PM by Hibernate Tools 3.2.1.GA



/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private FechaEntrega fechaEntrega;
     private FechaCompra fechaCompra;
     private Proveedor proveedor;

    public Compra() {
    }

    public Compra(FechaEntrega fechaEntrega, FechaCompra fechaCompra, Proveedor proveedor) {
       this.fechaEntrega = fechaEntrega;
       this.fechaCompra = fechaCompra;
       this.proveedor = proveedor;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public FechaEntrega getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(FechaEntrega fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public FechaCompra getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(FechaCompra fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }




}


