package com.pasantia.entidades;
// Generated 13/07/2013 11:12:50 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private Pais pais;
     private String nombreDepartamento;
     private Set divisionesUbicacions = new HashSet(0);
     private Set ciudads = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, Pais pais, String nombreDepartamento) {
        this.idDepartamento = idDepartamento;
        this.pais = pais;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(int idDepartamento, Pais pais, String nombreDepartamento, Set divisionesUbicacions, Set ciudads) {
       this.idDepartamento = idDepartamento;
       this.pais = pais;
       this.nombreDepartamento = nombreDepartamento;
       this.divisionesUbicacions = divisionesUbicacions;
       this.ciudads = ciudads;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set getDivisionesUbicacions() {
        return this.divisionesUbicacions;
    }
    
    public void setDivisionesUbicacions(Set divisionesUbicacions) {
        this.divisionesUbicacions = divisionesUbicacions;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


