package com.pasantia.entidades;
// Generated 13/07/2013 11:12:50 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private Producto producto;
     private FormaDePagar formaDePagar;
     private int cantidad;
     private long iva;
     private Long subtotal;
     private Long total;
     private Set ventas = new HashSet(0);
     private Set inventarios = new HashSet(0);

    public DetalleVenta() {
    }

	
    public DetalleVenta(Producto producto, FormaDePagar formaDePagar, int cantidad, long iva) {
        this.producto = producto;
        this.formaDePagar = formaDePagar;
        this.cantidad = cantidad;
        this.iva = iva;
    }
    public DetalleVenta(Producto producto, FormaDePagar formaDePagar, int cantidad, long iva, Long subtotal, Long total, Set ventas, Set inventarios) {
       this.producto = producto;
       this.formaDePagar = formaDePagar;
       this.cantidad = cantidad;
       this.iva = iva;
       this.subtotal = subtotal;
       this.total = total;
       this.ventas = ventas;
       this.inventarios = inventarios;
    }
   
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public FormaDePagar getFormaDePagar() {
        return this.formaDePagar;
    }
    
    public void setFormaDePagar(FormaDePagar formaDePagar) {
        this.formaDePagar = formaDePagar;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public long getIva() {
        return this.iva;
    }
    
    public void setIva(long iva) {
        this.iva = iva;
    }
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


