package com.pasantia.entidades;
// Generated 10/07/2013 05:30:45 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Divisiones generated by hbm2java
 */
public class Divisiones  implements java.io.Serializable {


     private Integer idDivisiones;
     private Departamento departamento;
     private String nombreDivision;
     private Set batallons = new HashSet(0);

    public Divisiones() {
    }

	
    public Divisiones(Departamento departamento, String nombreDivision) {
        this.departamento = departamento;
        this.nombreDivision = nombreDivision;
    }
    public Divisiones(Departamento departamento, String nombreDivision, Set batallons) {
       this.departamento = departamento;
       this.nombreDivision = nombreDivision;
       this.batallons = batallons;
    }
   
    public Integer getIdDivisiones() {
        return this.idDivisiones;
    }
    
    public void setIdDivisiones(Integer idDivisiones) {
        this.idDivisiones = idDivisiones;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreDivision() {
        return this.nombreDivision;
    }
    
    public void setNombreDivision(String nombreDivision) {
        this.nombreDivision = nombreDivision;
    }
    public Set getBatallons() {
        return this.batallons;
    }
    
    public void setBatallons(Set batallons) {
        this.batallons = batallons;
    }




}


