package com.pasantia.entidades;
// Generated 18/05/2013 04:10:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FormaDePagar generated by hbm2java
 */
public class FormaDePagar  implements java.io.Serializable {


     private Integer idFormaDePagar;
     private String nombrePago;
     private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);

    public FormaDePagar() {
    }

	
    public FormaDePagar(String nombrePago) {
        this.nombrePago = nombrePago;
    }
    public FormaDePagar(String nombrePago, Set<DetalleVenta> detalleVentas) {
       this.nombrePago = nombrePago;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getIdFormaDePagar() {
        return this.idFormaDePagar;
    }
    
    public void setIdFormaDePagar(Integer idFormaDePagar) {
        this.idFormaDePagar = idFormaDePagar;
    }
    public String getNombrePago() {
        return this.nombrePago;
    }
    
    public void setNombrePago(String nombrePago) {
        this.nombrePago = nombrePago;
    }
    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


