package com.pasantia.entidades;
// Generated 18/05/2013 04:10:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idPais;
     private Casino casino;
     private Departamento departamento;
     private String nombrePais;
     private Set<Casino> casinos = new HashSet<Casino>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Pais() {
    }

	
    public Pais(Casino casino, Departamento departamento, String nombrePais) {
        this.casino = casino;
        this.departamento = departamento;
        this.nombrePais = nombrePais;
    }
    public Pais(Casino casino, Departamento departamento, String nombrePais, Set<Casino> casinos, Set<Cliente> clientes) {
       this.casino = casino;
       this.departamento = departamento;
       this.nombrePais = nombrePais;
       this.casinos = casinos;
       this.clientes = clientes;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public Casino getCasino() {
        return this.casino;
    }
    
    public void setCasino(Casino casino) {
        this.casino = casino;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Casino> getCasinos() {
        return this.casinos;
    }
    
    public void setCasinos(Set<Casino> casinos) {
        this.casinos = casinos;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


