package com.pasantia.entidades;
// Generated 18/05/2013 04:10:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Vendedores vendedores;
     private String nombre;
     private String telefono;
     private String direccion;
     private String nit;
     private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Proveedor() {
    }

	
    public Proveedor(Vendedores vendedores, String nombre, String telefono, String direccion, String nit) {
        this.vendedores = vendedores;
        this.nombre = nombre;
        this.telefono = telefono;
        this.direccion = direccion;
        this.nit = nit;
    }
    public Proveedor(Vendedores vendedores, String nombre, String telefono, String direccion, String nit, Set<DetalleCompra> detalleCompras, Set<Compra> compras) {
       this.vendedores = vendedores;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.nit = nit;
       this.detalleCompras = detalleCompras;
       this.compras = compras;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


