package com.pasantia.entidades;
// Generated 13/07/2013 11:12:50 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {


     private Integer idSexo;
     private String nombreSexo;
     private Set personas = new HashSet(0);

    public Sexo() {
    }

	
    public Sexo(String nombreSexo) {
        this.nombreSexo = nombreSexo;
    }
    public Sexo(String nombreSexo, Set personas) {
       this.nombreSexo = nombreSexo;
       this.personas = personas;
    }
   
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }
    public String getNombreSexo() {
        return this.nombreSexo;
    }
    
    public void setNombreSexo(String nombreSexo) {
        this.nombreSexo = nombreSexo;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


