package com.pasantia.entidades;
// Generated 10/07/2013 10:05:50 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPersona generated by hbm2java
 */
public class TipoPersona  implements java.io.Serializable {


     private Integer idTipoPersona;
     private String nombreTipoPersona;
     private Set personas = new HashSet(0);

    public TipoPersona() {
    }

	
    public TipoPersona(String nombreTipoPersona) {
        this.nombreTipoPersona = nombreTipoPersona;
    }
    public TipoPersona(String nombreTipoPersona, Set personas) {
       this.nombreTipoPersona = nombreTipoPersona;
       this.personas = personas;
    }
   
    public Integer getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(Integer idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    public String getNombreTipoPersona() {
        return this.nombreTipoPersona;
    }
    
    public void setNombreTipoPersona(String nombreTipoPersona) {
        this.nombreTipoPersona = nombreTipoPersona;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


