package com.pasantia.entidades;
// Generated 14/08/2013 07:56:36 AM by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Persona persona;
     private Rol rol;
     private String clave;
     private String nomusuario;
     private int activo;

    public Usuario() {
    }

    public Usuario(Persona persona, Rol rol, String clave, String nomusuario, int activo) {
       this.persona = persona;
       this.rol = rol;
       this.clave = clave;
       this.nomusuario = nomusuario;
       this.activo = activo;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNomusuario() {
        return this.nomusuario;
    }
    
    public void setNomusuario(String nomusuario) {
        this.nomusuario = nomusuario;
    }
    public int getActivo() {
        return this.activo;
    }
    
    public void setActivo(int activo) {
        this.activo = activo;
    }




}


