package com.pasantia.entidades;
// Generated 18/05/2013 04:10:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Rol rol;
     private Cargo cargo;
     private String nombres;
     private String apellidos;
     private String cedula;
     private byte[] imagen;
     private String pass;
     private Set<Casino> casinos = new HashSet<Casino>(0);

    public Usuario() {
    }

	
    public Usuario(Rol rol, Cargo cargo, String nombres, String apellidos, String cedula, String pass) {
        this.rol = rol;
        this.cargo = cargo;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.cedula = cedula;
        this.pass = pass;
    }
    public Usuario(Rol rol, Cargo cargo, String nombres, String apellidos, String cedula, byte[] imagen, String pass, Set<Casino> casinos) {
       this.rol = rol;
       this.cargo = cargo;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.cedula = cedula;
       this.imagen = imagen;
       this.pass = pass;
       this.casinos = casinos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set<Casino> getCasinos() {
        return this.casinos;
    }
    
    public void setCasinos(Set<Casino> casinos) {
        this.casinos = casinos;
    }




}


